server:
  port: 8000

spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/khaleesi?useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      # 60 초
      connection-timeout: 60000
      maximum-pool-size: 10

  flyway:
    locations: classpath:db/migration/{vendor}
    # test 용도 나중에는 지워야 함
    clean-on-validation-error: true