server:
  port: 8000

spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/khaleesi?useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 60000
      maximum-pool-size: 10

  flyway:
    locations: classpath:db/migration/{vendor}